Added a scientific calculator
ridsuteri/Awesome-Chrome-Extensions pull request #138
Opened 2022-03-26 16:39 UTC by Girlwithasmile

### 🛠️ Fixes Issue

#76 

### 👨‍💻 Changes proposed

### ✔️ Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

## 📷 Screenshots
![Scientific calculator](https://user-images.githubusercontent.com/98261167/160248956-c56deb0b-69be-4503-8410-04b576bd676d.gif)
![Scientific calc preview](https://user-images.githubusercontent.com/98261167/160248972-9ea0f044-bce4-4d61-bb2f-07a4d1940354.png)

2022-03-27 10:20 UTC, ridsuteri commented on Scientific Calculator/manifest.json
> +        "default_icon":
add a icon here

2022-03-27 10:21 UTC, ridsuteri requested changes
@Girlwithasmile there is some issue within manifest file, please resolve that

2022-04-12 03:35 UTC, ridsuteri commented
updates @Girlwithasmile ?

2022-04-18 09:07 UTC, kalashvasaniya commented
> updates @Girlwithasmile ?

@ridsuteri if @Girlwithasmile not working on this issue assign this to me :)

2022-04-18 17:00 UTC, ridsuteri commented
> > updates @Girlwithasmile ?
> 
> @ridsuteri if @Girlwithasmile not working on this issue assign this to me :)

The existing calculator performs scientific operations too, hence there is no need of this issue now :(

2022-04-18 17:00 UTC, closed without merging

2022-04-18 17:33 UTC, kalashvasaniya commented
> > > updates @Girlwithasmile ?
> > 
> > 
> > @ridsuteri if @Girlwithasmile not working on this issue assign this to me :)
> 
> The existing calculator performs scientific operations too, hence there is no need of this issue now :(

okk :)